### ISSUE TITLE
Videos aur images ki link ko spreadsheet se kaise add kre ?

### ISSUE THREAD

**Issue by sahujaunpuri** [RahulJanagouda/StatusStories#16]
Rahul bhaee 
Videos aur images ki link ko spreadsheet se kaise add kre ?

**Comment by pritesh25** [comment]
@sahujaunpuri  extract data from spreadsheet to arrayList then pass those data to StoryActivity

**Comment by sahujaunpuri** [comment]
@pritesh25  bhaee mujhe koee spreadsheet ka example code ka link de dijiye.
