### ISSUE TITLE
Skipping and reversing not working

### ISSUE THREAD

**Issue by MalcolmMcFly** [RahulJanagouda/StatusStories#5]
Could you consider adding onClickListeners to the images so when they are tapped, it goes to the next story. I see that StoryStatusView has skip() and reverse() methods but they don't seem to be working. Am I mistaken?

**Comment by RahulJanagouda** [comment]
Next and previous do work. Its just that you need to click on the left edge and right edge. Is shown in the gif or demo video.

**Comment by MalcolmMcFly** [comment]
Confirmed, please close. Thank you :-)

**Comment by RahulJanagouda** [comment]
Cool :)
