### ISSUE TITLE
support library issue

### ISSUE THREAD

**Issue by MuhammedRefaat** [RahulJanagouda/StatusStories#6]
there is an issue on your gradle build which prevents the library from compiling, apparently it can't find the support library **26.1.0** as I think it should be **26.0.1** just like the **buildToolsVersion**:
```
dependencies {
.
    implementation 'com.android.support:appcompat-v7:26.1.0'
.
.
}
```

**Comment by RahulJanagouda** [comment]
Nope, it is a 26.1.0 post is linked below.
https://developer.android.com/topic/libraries/support-library/revisions.html#26-1-0
Please make sure that you have added Google repo in Gradle dependencies.
