### ISSUE TITLE
storyStatusView.pause(); Not working 

### ISSUE THREAD

**Issue by knowamit** [RahulJanagouda/StatusStories#7]
`storyStatusView.pause();`
Not working on the Status Stories while Downloading the Image, Slide still got skipped while download is not complete

**Comment by amitsharma492** [comment]
Try to Use Inside handler and post-execute 
``storyStatusView.pause();``
```
public void pauseView() {
        new Handler().post(new Runnable() {
            @Override
            public void run() {
                storyStatusView.pause();
            }
        });
    }

**Comment by UwaisWisitech** [comment]
I am facing same issue, above solution is not working.

**Comment by truptigoqii** [comment]
@knowamit thanks its working for me.
